### ISSUE TITLE
non-enrolled users appearing in course's journal activity

### ISSUE THREAD

**Issue by will-bulluck** [elearningsoftware/moodle-mod_journal#88] opened 2022-09-30 17:40 UTC
Moodle version: 3.9
Plugin version: 4.0.1 (Build: 2022091600)

On the mod_journal page it shows the non enrolled users with no entries

Please let me know if you need anything else.

**Comment by adrian-sarmas** [comment] 2023-04-24 11:07
Please give me more details @will-bulluck . The journal entries page (mod/journal/report.php?id=x) only shows enrolled users.

**Comment by adrian-sarmas** [comment] 2024-12-01 15:17
I’m unable to reproduce this issue with the latest version of the plugin, so I assume it has been resolved with the recent updates to the privacy provider class. I’ll go ahead and close this for now. @will-bulluck, if you’re still encountering this issue using the latest version on the master branch, please feel free to add a new comment.

**Closed by adrian-sarmas** 2024-12-01 15:17 UTC
Labels: Bug
