### ISSUE TITLE
Keep getting email:  An exception occurred during the processing of privacy data

### ISSUE THREAD

**Issue by neeesn** [elearningsoftware/moodle-mod_journal#110] opened 2024-11-28 07:18 UTC
We keep getting these emails from moodle:

Subject: Der opstod en undtagelse under behandling af privatlivsdata 
Der opstod en undtagelse ved kald af mod_journal\privacy\provider::delete_data_for_user.
Det betyder at plugin'et mod_journal ikke gjorde databehandlingen færdig. Følgende information kan gives til udvikleren af plugin'et:
Fejl ved skrivning til database

Translated to eng:
Subject:   An exception occurred during the processing of privacy data
An exception occurred when calling mod_journal\privacy\provider::delete_data_for_user.
This means that the plugin mod_journal did not complete the data processing. The following information can be provided to the developer of the plugin:
Error writing to the database

 #0 /var/www/html/moodle/lib/dml/moodle_read_slave_trait.php(293): moodle_database->query_end()
#1 /var/www/html/moodle/lib/dml/mysqli_native_moodle_database.php(1820): mysqli_native_moodle_database->query_end()
#2 /var/www/html/moodle/mod/journal/classes/privacy/provider.php(243): mysqli_native_moodle_database->delete_records_select()
#3 /var/www/html/moodle/lib/moodlelib.php(7817): mod_journal\privacy\provider::delete_data_for_user()
#4 /var/www/html/moodle/privacy/classes/manager.php(578): component_class_callback()
#5 /var/www/html/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#6 /var/www/html/moodle/privacy/classes/manager.php(414): core_privacy\manager->handled_component_class_callback()
#7 /var/www/html/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(151): core_privacy\manager->delete_data_for_user()
#8 /var/www/html/moodle/lib/classes/cron.php(519): tool_dataprivacy\task\process_data_request_task->execute()
#9 /var/www/html/moodle/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task()
#10 /var/www/html/moodle/lib/classes/cron.php(128): core\cron::run_adhoc_tasks()
#11 /var/www/html/moodle/admin/cli/cron.php(186): core\cron::run_main_process()
#12 {main}

We are currently on Moodle 4.4.4 and using plugin version 20230915.

**Comment by adrian-sarmas** [comment] 2024-12-01 15:11
I’m unable to reproduce this issue with the latest version of the plugin, so I assume it has been resolved with the recent updates to the privacy provider class. I’ll go ahead and close this for now. @neeesn, if you’re still encountering this issue using the latest version on the master branch, please feel free to add a new comment.

**Closed by adrian-sarmas** 2024-12-01 15:11 UTC
Labels: Bug
